return {
["Sea King"] = { IsExalted = false, IsSongOfTheDeep = false },
    ["Lucky"] = { IsExalted = false, IsSongOfTheDeep = false },
    ["Clever"] = { IsExalted = false, IsSongOfTheDeep = false },
    ["Sea Overlord"] = { IsExalted = true, IsSongOfTheDeep = false },
    ["Scrapper"] = { IsExalted = false, IsSongOfTheDeep = false },
    ["Steady"] = { IsExalted = false, IsSongOfTheDeep = false },
    ["Divine"] = { IsExalted = false, IsSongOfTheDeep = false },
    ["Long"] = { IsExalted = false, IsSongOfTheDeep = false },
    ["Swift"] = { IsExalted = false, IsSongOfTheDeep = false },
    ["Mystical"] = { IsExalted = true, IsSongOfTheDeep = false },
    ["Blessed Song"] = { IsExalted = false, IsSongOfTheDeep = true },
    ["Immortal"] = { IsExalted = true, IsSongOfTheDeep = false },
    ["Herculean"] = { IsExalted = false, IsSongOfTheDeep = false },
    ["Noir"] = { IsExalted = false, IsSongOfTheDeep = false },
    ["Controlled"] = { IsExalted = false, IsSongOfTheDeep = false },
    ["Abyssal"] = { IsExalted = false, IsSongOfTheDeep = false },
    ["Invincible"] = { IsExalted = true, IsSongOfTheDeep = false },
    ["Wormhole"] = { IsExalted = false, IsSongOfTheDeep = false },
    ["Breezed"] = { IsExalted = false, IsSongOfTheDeep = false },
    ["Quantum"] = { IsExalted = true, IsSongOfTheDeep = false },
    ["Blessed"] = { IsExalted = false, IsSongOfTheDeep = false },
    ["Resilient"] = { IsExalted = false, IsSongOfTheDeep = false },
    ["Unbreakable"] = { IsExalted = false, IsSongOfTheDeep = false },
    ["Insight"] = { IsExalted = false, IsSongOfTheDeep = false },
    ["Hasty"] = { IsExalted = false, IsSongOfTheDeep = false },
    ["Quality"] = { IsExalted = false, IsSongOfTheDeep = false },
    ["Piercing"] = { IsExalted = true, IsSongOfTheDeep = false },
    ["Mutated"] = { IsExalted = false, IsSongOfTheDeep = false },
    ["Storming"] = { IsExalted = false, IsSongOfTheDeep = false },
    ["Anomalous"] = { IsExalted = true, IsSongOfTheDeep = false },
    ["Ghastly"] = { IsExalted = false, IsSongOfTheDeep = false },
}
