return {
    ["Alter"]             = "enchant",        -- f
    ["Ancient Isle"]      = "ancient",
    ["The Arch"]          = "arch",
    ["Atlantis"]          = "atlantis",       -- fixed
    ["Brine"]             = "brine",
    ["Bunker"]            = "bunker1",
    ["Camp 1"]            = "camp1",
    ["Camp 2"]            = "camp2",
    ["Ancient Archives"]  = "crafting",
    ["Desolate Pocket"]   = "deep",
    ["Glacial Gotto"]     = "finalpuzzle",
    ["Forsaken Shores"]   = "forsaken",
    ["Keepers Secret"]    = "gamma",          -- fixed
    ["Grand Reef"]        = "grandreef",
    ["Kraken Puzzle"]     = "krakendoor",     -- fixed
    ["Frigid Cavern"]     = "leverpuzzle",
    ["Sunstone Island"]   = "merlin",
    ["Moosewood"]         = "moosewood",
    ["Mushgroove swamp"]  = "mushgrove",      -- fixed
    ["Oilrig"]            = "oilrig",
    ["Poseidon Puzzle"]   = "poseidonpuzzle",
    ["Roslit"]            = "roslit",
    ["Snowcap Island"]    = "snow",
    ["Havesters Spike"]   = "spike",
    ["Statue of Sov"]     = "statue",
    ["Sunken Depths"]     = "sunkencave",     -- fixed
    ["Terrapin Island"]   = "terrapin",
    ["The Depths"]        = "thedepths",
    ["Trident Puzzle"]    = "trident",
    ["Vertigo"]           = "vertigo",
    ["Volcano"]           = "volcano",
    ["Upper Snowcap"]     = "wilson",
    ["Zeus Trial"]        = "zeuspuzzle"
}
