return {
    -- Special Price Cases
    ["UnRegistered"]                     = { Price = "No Price" }, -- No Price
    ["Flimsy Rod"]                       = { Price = "0" },        -- Free

    -- Low Price Rods
    ["Training Rod"]                     = { Price = "300" },
    ["Plastic Rod"]                      = { Price = "900" },
    ["Carbon Rod"]                       = { Price = "2000" },
    ["Stone Rod"]                        = { Price = "3000" },
    ["Long Rod"]                         = { Price = "4500" },
    ["Fast Rod"]                         = { Price = "4500" },
    ["Lucky Rod"]                        = { Price = "5250" },
    ["Steady Rod"]                       = { Price = "7000" },
    ["Nocturnal Rod"]                    = { Price = "11000" },
    ["Rapid Rod"]                        = { Price = "14000" },
    ["Magnet Rod"]                       = { Price = "15000" },
    ["Reinforced Rod"]                   = { Price = "20000" },
    ["Arctic Rod"]                       = { Price = "25000" },
    ["Avalanche Rod"]                    = { Price = "35000" },
    ["Crystalized Rod"]                  = { Price = "35000" },
    ["Firework Rod"]                     = { Price = "35000" },
    ["Depthseeker Rod"]                  = { Price = "40000" },
    ["Phoenix Rod"]                      = { Price = "40000" },
    ["Midas Rod"]                        = { Price = "55000" },
    ["Ice Warpers Rod"]                  = { Price = "65000" },
    ["Aurora Rod"]                       = { Price = "90000" },
    ["Mythical Rod"]                     = { Price = "110000" },
    ["Kings Rod"]                        = { Price = "120000" },
    ["Trident Rod"]                      = { Price = "150000" },
    ["Destiny Rod"]                      = { Price = "190000" },
    ["Volcanic Rod"]                     = { Price = "300000" },
    ["Summit Rod"]                       = { Price = "300000" },
    ["Rod Of The Depths"]                = { Price = "750000" },
    ["Kraken Rod"]                       = { Price = "1333333" },
    ["Poseidon Rod"]                     = { Price = "1555555" },
    ["Zeus Rod"]                         = { Price = "1700000" },
    ["Heaven's Rod"]                     = { Price = "1750000" },
    ["Tempest Rod"]                      = { Price = "1850000" },
    ["Challenger's Rod"]                 = { Price = "2500000" },
    ["Ethereal Prism Rod"]               = { Price = "15000000" },
    ["Rod Of The Zenith"]                = { Price = "10000000" },

    -- Infinite Price Rods
    ["Abyssal Spinecaster"]              = { Price = "inf" },
    ["Abyssal Specter Rod"]              = { Price = "inf" },
    ["Antler Rod"]                       = { Price = "inf" },
    ["Astral Rod"]                       = { Price = "inf" },
    ["Auric Rod"]                        = { Price = "inf" },
    ["Buddy Bond Rod"]                   = { Price = "inf" },
    ["Candy Cane Rod"]                   = { Price = "inf" },
    ["Celestial Rod"]                    = { Price = "inf" },
    ["Champions Rod"]                    = { Price = "inf" },
    ["Clickbait Caster"]                 = { Price = "inf" },
    ["CocoRod"]                          = { Price = "inf" },
    ["Courage Bat"]                      = { Price = "inf" },
    ["Developers Rod"]                   = { Price = "inf" },
    ["Electric Guitar"]                  = { Price = "inf" },
    ["Evil Pitchfork of Doom Rod"]       = { Price = "inf" },
    ["Event Horizon Rod"]                = { Price = "inf" },
    ["Fabulous Rod"]                     = { Price = "inf" },
    ["Fischmas Rod"]                     = { Price = "inf" },
    ["Fortune Rod"]                      = { Price = "inf" },
    ["Frost Warden Rod"]                 = { Price = "inf" },
    ["Frostbane Rod"]                    = { Price = "inf" },
    ["Frostfire Rod"]                    = { Price = "inf" },
    ["Fungal Rod"]                       = { Price = "inf" },
    ["Haunted Rod"]                      = { Price = "inf" },
    ["Katana Rod"]                       = { Price = "inf" },
    ["Leviathan's Fang Rod"]             = { Price = "inf" },
    ["Magma Rod"]                        = { Price = "inf" },
    ["Mila's Wand Of Magic"]             = { Price = "inf" },
    ["Miku's Melody"]                    = { Price = "inf" },
    ["Nates Blade"]                      = { Price = "inf" },
    ["No-Life Rod"]                      = { Price = "inf" },
    ["North-Star Rod"]                   = { Price = "inf" },
    ["Pen Rod"]                          = { Price = "inf" },
    ["Polaris Serenade"]                 = { Price = "inf" },
    ["Precision Rod"]                    = { Price = "inf" },
    ["Prismatic Rod"]                    = { Price = "inf" },
    ["Rapid Rod"]                        = { Price = "inf" },
    ["ReRod"]                            = { Price = "inf" },
    ["Relic Rod"]                        = { Price = "inf" },
    ["Resourceful Rod"]                  = { Price = "inf" },
    ["Rod Of The Eternal King"]          = { Price = "inf" },
    ["Rod Of The Exalted One"]           = { Price = "inf" },
    ["Rod Of The Forgotten Fang"]        = { Price = "inf" },
    ["Riptide Rod"]                      = { Price = "inf" },
    ["Seraphic Rod"]                     = { Price = "inf" },
    ["Seasons Rod"]                      = { Price = "inf" },
    ["Sovereign Doombringer"]            = { Price = "inf" },
    ["Steady Rod"]                       = { Price = "inf" },
    ["Sunken Rod"]                       = { Price = "inf" },
    ["Test Rod"]                         = { Price = "inf" },
    ["The Brick Rod"]                    = { Price = "inf" },
    ["The Lost Rod"]                     = { Price = "inf" },
    ["The Twig"]                         = { Price = "inf" },
    ["Tryhard Rod"]                      = { Price = "inf" },
    ["Ultratech Rod"]                    = { Price = "inf" },
    ["Venomfang Rod"]                    = { Price = "inf" },
    ["Voyager Rod"]                      = { Price = "inf" },
    ["Wisdom Rod"]                       = { Price = "inf" },
    ["Yin Yang Rod"]                     = { Price = "inf" },
    ["Zeus Rod"]                         = { Price = "inf" },
}
