return {
        ["Long Rod"] = { Price = "4500" },
        ["Developers Rod"] = { Price = "inf" },
        ["Frost Warden Rod"] = { Price = "inf" },
        ["Mystic Staff"] = { Price = "inf" },
        ["Fortune Rod"] = { Price = "12750" },
        ["Rod Of The Zenith"] = { Price = "10000000" },
        ["Riptide Rod"] = { Price = "inf" },
        ["Fischmas Rod"] = { Price = "inf" },
        ["Courage Bat"] = { Price = "inf" },
        ["Resourceful Rod"] = { Price = "inf" },
        ["Heaven's Rod"] = { Price = "1750000" },
        ["Summit Rod"] = { Price = "300000" },
        ["Midas Rod"] = { Price = "55000" },
        ["Evil Pitchfork of Doom Rod"] = { Price = "inf" },
        ["Steady Rod"] = { Price = "7000" },
        ["Champions Rod"] = { Price = "80000" },
        ["Frostbane Rod"] = { Price = "inf" },
        ["Training Rod"] = { Price = "300" },
        ["Phoenix Rod"] = { Price = "40000" },
        ["???"] = { Price = "inf" },
        ["Relic Rod"] = { Price = "inf" },
        ["Executive Rod"] = { Price = "inf" },
        ["Voyager Rod"] = { Price = "inf" },
        ["Kraken Rod"] = { Price = "1333333" },
        ["Fabulous Rod"] = { Price = "inf" },
        ["Avalanche Rod"] = { Price = "35000" },
        ["No-Life Rod"] = { Price = "inf" },
        ["Event Horizon Rod"] = { Price = "inf" },
        ["Leviathan's Fang Rod"] = { Price = "1000000" },
        ["Test Rod"] = { Price = "inf" },
        ["Flimsy Rod"] = { Price = "0" },
        ["Ice Warpers Rod"] = { Price = "65000" },
        ["Carbon Rod"] = { Price = "2000" },
        ["Arctic Rod"] = { Price = "25000" },
        ["Frostfire Rod"] = { Price = "inf" },
        ["Magnet Rod"] = { Price = "15000" },
        ["Magma Rod"] = { Price = "inf" },
        ["Nates Blade"] = { Price = "inf" },
        ["Astral Rod"] = { Price = "inf" },
        ["Katana Rod"] = { Price = "inf" },
        ["Tempest Rod"] = { Price = "1850000" },
        ["ReRod"] = { Price = "inf" },
        ["Rapid Rod"] = { Price = "14000" },
        ["Rod Of The Depths"] = { Price = "750000" },
        ["Challenger's Rod"] = { Price = "2500000" },
        ["Aurora Rod"] = { Price = "90000" },
        ["Tryhard Rod"] = { Price = "inf" },
        ["Electric Guitar"] = { Price = "inf" },
        ["Venomfang Rod"] = { Price = "inf" },
        ["Pen Rod"] = { Price = "inf" },
        ["The Lost Rod"] = { Price = "inf" },
        ["Mila's Wand Of Magic"] = { Price = "inf" },
        ["Miku's Melody"] = { Price = "inf" },
        ["Abyssal Specter Rod"] = { Price = "1000000" },
        ["Fast Rod"] = { Price = "4500" },
        ["Crystalized Rod"] = { Price = "35000" },
        ["Firework Rod"] = { Price = "35000" },
        ["The Twig"] = { Price = "inf" },
        ["Krampus's Rod"] = { Price = "inf" },
        ["Rod Of The Exalted One"] = { Price = "inf" },
        ["Rod Of The Forgotten Fang"] = { Price = "inf" },
        ["Rod Of The Eternal King"] = { Price = "inf" },
        ["Polaris Serenade"] = { Price = "inf" },
        ["Lucky Rod"] = { Price = "5250" },
        ["Fischer's Rod"] = { Price = "inf" },
        ["UnRegistered"] = { Price = "No Price" },
        ["Wisdom Rod"] = { Price = "inf" },
        ["Abyssal Spinecaster"] = { Price = "inf" },
        ["Stone Rod"] = { Price = "3000" },
        ["Scurvy Rod"] = { Price = "50000" },
        ["Mythical Rod"] = { Price = "110000" },
        ["Kings Rod"] = { Price = "120000" },
        ["Prismatic Rod"] = { Price = "inf" },
        ["Volcanic Rod"] = { Price = "300000" },
        ["Sunken Rod"] = { Price = "inf" },
        ["Yin Yang Rod"] = { Price = "inf" },
        ["Haunted Rod"] = { Price = "inf" },
        ["Brick Rod"] = { Price = "13337" },
        ["Fungal Rod"] = { Price = "inf" },
        ["Ethereal Prism Rod"] = { Price = "15000000" },
        ["Poseidon Rod"] = { Price = "1555555" },
        ["Antler Rod"] = { Price = "inf" },
        ["Destiny Rod"] = { Price = "190000" },
        ["Rex Umbrarum"] = { Price = "inf" },
        ["Nocturnal Rod"] = { Price = "11000" },
        ["Trident Rod"] = { Price = "150000" },
        ["Zeus Rod"] = { Price = "1700000" },
        ["Buddy Bond Rod"] = { Price = "inf" },
        ["Tetra Rod"] = { Price = "inf" },
        ["Auric Rod"] = { Price = "inf" },
        ["Seraphic Rod"] = { Price = "inf" },
        ["Reinforced Rod"] = { Price = "20000" },
        ["Seasons Rod"] = { Price = "inf" },
        ["Ultratech Rod"] = { Price = "inf" },
        ["Sovereign Doombringer"] = { Price = "inf" },
        ["Clickbait Caster"] = { Price = "inf" },
        ["The Brick Rod"] = { Price = "inf" },
        ["Celestial Rod"] = { Price = "inf" },
        ["Precision Rod"] = { Price = "inf" },
        ["CocoRod"] = { Price = "inf" },
        ["Depthseeker Rod"] = { Price = "40000" },
        ["Plastic Rod"] = { Price = "900" },
        ["Candy Cane Rod"] = { Price = "inf" },
        ["North-Star Rod"] = { Price = "inf" },
}
